AWSTemplateFormatVersion: "2010-09-09"
Description: Plantilla para Tomcat
Resources: 
    TomcatSecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
          GroupDescription: Grupo de Seguridad para Tomcat para puertos 8080 y 22
          GroupName: TomcatSecurityGroup
          SecurityGroupIngress: 
            - Description: Tomcat Port
              IpProtocol: TCP
              FromPort: 8080
              ToPort: 8080
              CidrIp: 0.0.0.0/0
            - IpProtocol: TCP
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0
    EC2Intance:
        Type: "AWS::EC2::Instance"
        Properties:
          ImageId: ami-06aa3f7caf3a30282
          InstanceType: t2.medium
          IamInstanceProfile: LabInstanceProfile
          KeyName: vockey
          SecurityGroupIds: 
            - !Ref TomcatSecurityGroup
          Tags:
            - Key: Name 
              Value: TomcatServer